#!/bin/bash


for line in $(find . -maxdepth 3 -type d -name .git -print)
do
	echo "Processing $line"
	cd "$line/.."
	if [[ "$1" == "composer" ]];
	then
		if [[ ! -z "$4" ]];
		then
			composer $2 $3 $4 2> /dev/null &
		elif [[ ! -z "$3" ]];
		then
			composer $2 $3 2> /dev/null &
		else
			composer $2 2> /dev/null &
		fi
	elif [[ ! -z "$3" ]];
	then
		git $1 $2 $3 2> /dev/null &
	elif [[ ! -z "$2" ]];
	then
		git $1 $2 2> /dev/null &
	else
		git $1 2> /dev/null &
	fi
	cd -
done
